name: 获取V2ray订阅
on:
  # schedule: #UTC+0               #UTC+8
  #   - cron: '*/35 0-8 * * 1-5'   #工作日 上午8:00 - 下午4:00
  #   - cron: '*/25 8-14 * * 1-5'  #工作日 下午4:00 - 晚上10:00
  #   - cron: '*/55 14-21 * * 1-4' #工作日 晚上10:00 - 次日凌晨5:00
  #   - cron: '*/25 21-23 * * 1-5' #工作日 次日凌晨5:00 - 次日上午8:00
  #   - cron: '*/25 14-21 * * 5'   #星期五 晚上10:00 - 次日凌晨5:00
  #   - cron: '*/25 * * * 0,6'     #休息日 全天候
  workflow_dispatch:
    watch:
      types: started
    repository_dispatch:
      types: get_v2ray
permissions:
  contents: write
jobs:
  get_v2ray:
    runs-on: ubuntu-latest
    steps:
      - name: 设置SSH私钥信息
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.token_Private_Keys }}
      - name: 检出代码
        uses: actions/checkout@v2
      - name: '安装python环境'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: '安装依赖'
        run: |
          pip install -r requirements.txt
      - name: 设置githup信息
        env:
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
        run: |
          git config --global user.name "$username"
          git config --global user.email "$email"
      - name: 获取订阅
        run: |
          python3 get_clash.py
          git add pub
          git pull
          git commit --allow-empty -m "up"
          git push
      - name: 同步到gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/ronghuaxueleng
          dst: gitee/getready
          static_list: "get_v2"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
      - name: 删除过多的workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: 1
